apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/pranay1404/argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
