apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami 
      #path: bitnami
    chart: metrics-server
    targetRevision: 6.6.1
    helm:
      releaseName: metrics-server
      values: |
        extraArgs:
        - --kubelet-insecure-tls=true
        # Values specific to the Metrics Server Helm chart
        replicas: 2
        resources:
          requests:
            memory: "100Mi"  # Set resource requests as needed
            cpu: "100m"
          limits:
            memory: "200Mi"  # Set resource limits as needed
            cpu: "200m"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
