# sealed-secrets                      	1.5.11 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami 
      #path: bitnami
    chart: sealed-secrets
    targetRevision: 1.5.11
    helm:
      releaseName: sealed-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
